default: &default
  adapter: postgresql
  url: <%= ENV["POSTGRES_URL"] || ENV["DATABASE_URL"] %>
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: missa-simplex-dev

test:
  <<: *default
  database: missa-simplex-test

